apijmps:
	jmp word jaspos
	jmp word jaspos_monitor_clear
	jmp word jaspos_monitor_dispstring
	jmp word jaspos_monitor_dispchar
	jmp word jaspos_monitor_getcursorxy
	jmp word jaspos_monitor_init
	jmp word jaspos_keyb_getkey
	jmp word jaspos_keyb_getstring
	jmp word jaspos_strutils_d2str
	jmp word jaspos_strutils_compare
	jmp word jaspos_strutils_hex2str
	jmp word jaspos_strutils_instr
	jmp word jaspos_strutils_strlen
	jmp word jaspos_strutils_tolower
	jmp word jaspos_strutils_toupper
	jmp word jaspos_strutils_trimleading
	jmp word jaspos_strutils_trimtrailing
	jmp word jaspos_strutils_trim
	jmp word jaspos_disk_readsector
	jmp word jaspos_disk_reset
	jmp word jaspos_power_connect
	jmp word jaspos_power_shutdown